owners = []
nickname = "alis-bot-rs"
#nick_password = "testtest"
alt_nicks = ["alis-bot-rs_", "alis-bot-rs__"]
username = "alis-bot-rs"
realname = "Test User"
#server = "chat.freenode.net"
server = "irc.geeknode.org"
#port = 6697
#password = ""
#proxy_type = "None"
#proxy_server = "127.0.0.1"
#proxy_port = "1080"
#proxy_username = ""
#proxy_password = ""
#use_tls = true
#cert_path = "cert.der"
#client_cert_path = "client.der"
#client_cert_pass = "password"
encoding = "UTF-8"
#channels = ["#bot-test-room"]
#umodes = "+RB-x"
#user_info = "I'm a test user for the irc crate."
#version = "irc:git:Rust"
#source = "https://github.com/aatxe/irc"
#ping_time = 180
#ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
#should_ghost = false
#ghost_sequence = []

[channel_keys]
#"#fake" = "password"

[options]
note = "anything you want can be in here!"
and = "you can use it to build your own additional configuration options."
key = "value"
