owners = []
nickname = "alis-bot-rs"
#nick_password = "password"
alt_nicks = ["alis-bot-rs_", "alis-bot-rs__"]
username = "alis-bot-rs"
realname = "Alis BotRs"
server = "irc.libera.chat"
#port = 6697
#password = ""
proxy_type = "None"
proxy_server = "127.0.0.1"
proxy_port = "1080"
#proxy_username = ""
#proxy_password = ""
use_tls = false
#cert_path = "cert.der"
#client_cert_path = "client.der"
#client_cert_pass = "password"
encoding = "UTF-8"
#umodes = "+RB-x"
user_info = "I'm bot allowing to search with more flexilibity than the /LIST command"
version = "irc:git:Rust"
source = "https://github.com/precambrien/alis-bot-rs"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
ghost_sequence = []

